use master

CREATE TABLE DEPOSIT (
ACTNO VARCHAR(5) PRIMARY KEY,
CNAME VARCHAR(18) ,
BNAME VARCHAR(18) ,
AMOUNT int,
ADATE DATE);

CREATE TABLE BRANCH(
BNAME VARCHAR(18) PRIMARY KEY,
CITY VARCHAR(18)
);

CREATE TABLE CUSTOMER(
CNAME VARCHAR(19) PRIMARY KEY,
CITY VARCHAR(18)
);

CREATE TABLE BORROW (
LOANNO VARCHAR(5) PRIMARY KEY,
CNAME VARCHAR(18) ,
BNAME VARCHAR(18),
AMOUNT INT
);

INSERT INTO DEPOSIT VALUES ('100','ANIL','VRCE',1000.00,'1-MAR-95');
INSERT INTO DEPOSIT VALUES ('101','SUNIL','AJNI',5000.00, '4-JAN-96')
INSERT INTO DEPOSIT VALUES ('102','MEHUL','KAROLBAGH',3500.00,'17-NOV-95'); 
INSERT INTO DEPOSIT VALUES ('104','MADHURI','CHANDNI',1200.00,'17-DEC-95'); 
INSERT INTO DEPOSIT VALUES ('105','PRAMOD','M.G.ROAD',3000.00,'27-MAR-96'); 
INSERT INTO DEPOSIT VALUES ('106','SANDIP','ANDHERI',2000.00,'31-MAR-96');
INSERT INTO DEPOSIT VALUES ('107','SHIVANI','VIRAR',1000.00,'5-SEP-95');
INSERT INTO DEPOSIT VALUES ('108','KRANTI','NEHRU PLACE',5000.00,'2-JUL-95');
INSERT INTO DEPOSIT VALUES('109','NAREN','POWAI',7000.00,'10-AUG-95');

SELECT * FROM DEPOSIT

INSERT INTO BRANCH VALUES ('VRCE','NAGPUR');
INSERT INTO BRANCH VALUES ('AJNI','NAGPUR');
INSERT INTO BRANCH VALUES ('KAROLBAGH','DELHI');
INSERT INTO BRANCH VALUES ('CHANDNI','DELHI');
INSERT INTO BRANCH VALUES ('DHARAMPETH','NAGPUR');
INSERT INTO BRANCH VALUES ('M.G.ROAD','BANGLORE');
INSERT INTO BRANCH VALUES ('ANDHERI','MUMBAI'); 
INSERT INTO BRANCH VALUES ('VIRAR','MUMBAI');
INSERT INTO BRANCH VALUES ('NEHRU PLACE','DELHI');
INSERT INTO BRANCH VALUES ('POWAI','MUMBAI');

SELECT * FROM BRANCH


INSERT INTO CUSTOMER VALUES ('ANIL','KOLKATA');
INSERT INTO CUSTOMER VALUES ('SUNIL','DELHI');
INSERT INTO CUSTOMER VALUES ('MEHUL','BARODA');
INSERT INTO CUSTOMER VALUES ('MANDAR','PATNA');
INSERT INTO CUSTOMER VALUES ('MADHURI','NAGPUR');
INSERT INTO CUSTOMER VALUES ('PRAMOD','NAGPUR');
INSERT INTO CUSTOMER VALUES ('SANDIP','SURAT');
INSERT INTO CUSTOMER VALUES ('SHIVANI','MUMBAI');
INSERT INTO CUSTOMER VALUES ('KRANTI','MUMBAI');
INSERT INTO CUSTOMER VALUES ('NAREN','MUMBAI');

SELECT * FROM CUSTOMER

INSERT INTO BORROW VALUES ('201','ANIL','VRCE',1000);
INSERT INTO BORROW VALUES ('206','MEHUL','AJNI',5000);
INSERT INTO BORROW VALUES ('311','SUNIL','DHARAMPETH',3000);
INSERT INTO BORROW VALUES ('321','MADHURI','ANDHERI',2000);
INSERT INTO BORROW VALUES ('375','PRAMOD','VIRAR',8000); 
INSERT INTO BORROW VALUES ('481','KRANTI','NEHRU PLACE',3000);

SELECT * FROM BORROW

--Q1:Create a Store Procedure which will accept name of the customer as input parameter and product the following output, 
--List Names of Customers who are Depositors and have Same Branch City as that of input parameter customer�s Name.

CREATE PROCEDURE CusTName
@Name NVARCHAR(50)
AS
BEGIN
	SELECT CNAME FROM DEPOSIT AS D
	INNER JOIN BRANCH AS B
	ON D.BNAME = B.BNAME
	WHERE B.CITY = 	(SELECT B.CITY
			FROM BRANCH AS B
			INNER JOIN DEPOSIT AS D
			ON B.BNAME = D.BNAME
			WHERE CNAME = @Name)
END

EXECUTE CustName 'NAREN';


--Q2: Create a Store Procedure which will accept name of the customer as input parameter and produce the following output List in JSON format,
--All the Depositors Having Depositors Having Deposit in All the Branches where input parameter customer is Having an Account

CREATE PROCEDURE GetDepositorByName @Name NVARCHAR(50),@JSONOUT NVARCHAR(MAX) OUTPUT
AS 
BEGIN
	SELECT Cname FROM Deposits WHERE Bname IN (
        SELECT DISTINCT Bname FROM Deposits WHERE Cname = @name
    )  GROUP BY Cname HAVING COUNT(*) = (SELECT count(Bname) FROM Deposits WHERE Cname = @name)
    FOR JSON PATH, ROOT ('Depositors')
	
	WHERE Cname = @Name) FOR JSON AUTO
END
DROP PROCEDURE GetDepositorByName

DECLARE @JsonOutput NVARCHAR(MAX)
EXECUTE GetDepositorByName 'Shivani',@JsonOutput OUTPUT
PRINT @JsonOutput



--Q3: Create a Store Procedure that will accept city name and returns the number of customers in that city.

CREATE PROCEDURE CusCity 
@CITY NVARCHAR(50)
AS 
BEGIN
	RETURN (SELECT Count(CNAME) FROM CUSTOMER WHERE CITY = @CITY)
END

DECLARE @CustCount int
EXECUTE @CustCount = CusCity 'Mumbai'
PRINT @CustCount



--Q4: Create a Store Procedure which will accept city of the customer as input parameter and product the following output List in JSON format List All 
--the Customers Living in city provided in input parameter and Having the Branch City as MUMBAI or DELHI


CREATE PROCEDURE CusCity
@City NVARCHAR(50)
AS
BEGIN
		SELECT C.CNAME
		FROM DEPOSIT AS D
		INNER JOIN BRANCH AS B
		ON D.BNAME = B.BNAME
		INNER JOIN Customer  AS C
		ON C.Cname = D.Cname
		WHERE B.City = 'Mumbai' OR B.City = 'Delhi' 
		AND C.City = @City
END

EXECUTE GetCusDetailByCity 'Mumbai'

--Q5: Count the Number of Customers Living in the City where Branch is Located
CREATE PROCEDURE COUNT_CUS
AS
SET NOCOUNT ON;

SELECT COUNT(d.CNAME) 
FROM DEPOSIT d
JOIN BRANCH b 
ON d.BNAME = b.BNAME
WHERE b.CITY IS NOT NULL AND d.BNAME IS NOT NULL 
GO

EXECUTE COUNT_CUS

--Q6: Create a Procedure which will accept input in JSON parameter CustomerName,City, ACTNO,Branch,amount  
--And insert these record in the Deposit table. Before inserting some validation should be done like amount
--should be greater than 10Rs. and date should always be current date.

CREATE PROCEDURE JsonToTable
@JSONVAL NVARCHAR(MAX)
AS
BEGIN
	
	INSERT INTO DEPOSIT(ACTNO,CNAME,BNAME,AMOUNT)
	SELECT ACTNO,CNAME,BNAME,AMOUNT
	FROM OPENJSON(@JSONVAL)
	WITH (ACTNO NVARCHAR(5) ,
			CNAME NVARCHAR(18),
			BNAME NVARCHAR(18),
			AMOUNT INT)
END


DECLARE @JSON NVARCHAR(MAX)
SET @JSON = '[{"CNAME" : "ABC","ACTNO" : 143,"BNAME" : "RAJKOT, "AMOUNT" : "5000" }]'
EXECUTE JsonToTable @JSON

SELECT * FROM DEPOSIT

